const itemsArr = [
  {
    id: 0,
    brand: "AJ-luxe",
    name: "Cartoon Astronaut T-shirts",
    price: 100.99,
    image: "images/products/f1.jpg",
    count: 1,
  },
  {
    id: 1,
    brand: "AJ-luxe",
    name: "Cartoon Astronaut T-shirts",
    price: 120.99,
    image: "images/products/f2.jpg",
    count: 1,
  },
  {
    id: 2,
    brand: "AJ-luxe",
    name: "Cartoon Astronaut T-shirts",
    price: 70.99,
    image: "images/products/f3.jpg",
    count: 1,
  },
  {
    id: 3,
    brand: "AJ-luxe",
    name: "Cartoon Astronaut T-shirts",
    price: 120.99,
    image: "images/products/f4.jpg",
    count: 1,
  },
  {
    id: 4,
    brand: "AJ-luxe",
    name: "Cartoon Astronaut T-shirts",
    price: 170.99,
    image: "images/products/f5.jpg",
    count: 1,
  },
  {
    id: 5,
    brand: "AJ-luxe",
    name: "Cartoon Astronaut T-shirts",
    price: 200.25,
    image: "images/products/f6.jpg",
    count: 1,
  },
  {
    id: 6,
    brand: "AJ-luxe",
    name: "Cartoon Astronaut T-shirts",
    price: 120.99,
    image: "images/products/f7.jpg",
    count: 1,
  },
  {
    id: 7,
    brand: "AJ-luxe",
    name: "Cartoon Astronaut T-shirts",
    price: 123.99,
    image: "images/products/f8.jpg",
    count: 1,
  },
  {
    id: 8,
    brand: "AJ-luxe",
    name: "Cartoon Astronaut T-shirts",
    price: 70.25,
    image: "images/products/n1.jpg",
    count: 1,
  },
  {
    id: 9,
    brand: "AJ-luxe",
    brand: "AJ-luxe",
    name: "Cartoon Astronaut T-shirts",
    price: 80.25,
    image: "images/products/n2.jpg",
    count: 1,
  },
  {
    id: 10,
    brand: "AJ-luxe",
    name: "Cartoon Astronaut T-shirts",
    price: 130.25,
    image: "images/products/n3.jpg",
    count: 1,
  },
  {
    id: 11,
    brand: "AJ-luxe",
    brand: "AJ-luxe",
    name: "Cartoon Astronaut T-shirts",
    price: 70.25,
    image: "images/products/n5.jpg",
    count: 1,
  },
  {
    id: 12,
    brand: "AJ-luxe",
    name: "Cartoon Astronaut T-shirts",
    price: 120.25,
    image: "images/products/n4.jpg",
    count: 1,
  },
  {
    id: 13,
    brand: "AJ-luxe",
    name: "Cartoon Astronaut T-shirts",
    price: 60.25,
    image: "images/products/n6.jpg",
    count: 1,
  },
  {
    id: 14,
    brand: "AJ-luxe",
    name: "Cartoon Astronaut T-shirts",
    price: 40.25,
    image: "images/products/n7.jpg",
    count: 1,
  },
  {
    id: 15,
    brand: "AJ-luxe",
    name: "Cartoon Astronaut T-shirts",
    price: 70.25,
    image: "images/products/n8.jpg",
    count: 1,
  },
];
